baseURL = '/'
languageCode = 'ja-jp'
title = 'imdkm'
theme = 'bearcub'
copyright = "imdkm"

[pagination]
  pagerSize = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  recentPostsLimit = 5  # 表示する最新記事の件数

enableGitInfo = true

[frontmatter]
  lastmod = ":git"